(rule
 (alias frama-c-configure)
 (deps (universe))
 (action (progn
          (echo "LocalTactics:" %{lib-available:frama-c-local-tactic.core} "\n")
          (echo "  - Wp:" %{lib-available:frama-c-wp.core} "\n")
  )
 )
)

(library
 (name LocalTactics)
 (optional)
 (public_name frama-c-local-tactic.core)
 (flags -open Frama_c_kernel :standard)
 (libraries frama-c.kernel frama-c-wp.core)
)

(plugin
 (optional)
 (name local-tactic)
 (libraries frama-c-local-tactic.core)
 (site (frama-c plugins)))
